name: 'HTTP Request Action'
description: 'Create any HTTP Request'
inputs:
    url:
        description: 'Request URL'
        required: true
    method:
        description: 'Request Method'
        required: false
        default: 'POST'
    http2:
        description: 'Upgrade to http2'
        required: false
        default: false
    contentType:
        description: 'Content Type'
        required: false
    data:
        description: 'Request Body as JSON String'
        required: false
        default: '{}'
    files:
        description: 'Map of absolute file paths as JSON String'
        required: false
        default: '{}'
    username:
        description: 'Auth Username'
        required: false
    password:
        description: 'Auth Password'
        required: false
    timeout:
        description: 'Request Timeout in Sec'
        required: false
        default: '5000'
    bearerToken:
        description: 'Bearer Authentication Token'
        required: false
    customHeaders:
        description: 'Custom HTTP Headers'
        required: false
    preventFailureOnNoResponse:
        description: 'Prevent this Action to fail if the request respond without an response'
        required: false
    ignoreStatusCodes:
        description: 'Prevent this Action to fail if the request respond with one of the configured StatusCodes'
        required: false
    escapeData:
        description: 'Escape newlines in data string content'
        required: false
outputs:
    responseHeaders:
        description: 'HTTP Response Headers'
    responseBody:
        description: 'HTTP Response Content'
runs:
    using: 'docker'
    image: 'Dockerfile'
