name: 'HTTP Request Action'
description: 'Create any HTTP Request'
inputs:
    url:
        description: 'Request URL'
        required: true
    method:
        description: 'Request Method'
        required: false
        default: 'POST'
    http2:
        description: 'Upgrade to http2'
        required: false
        default: False
    contentType:
        description: 'Content Type'
        required: false
    data:
        description: 'Request Body as JSON String'
        required: false
    body:
        description: 'Raw body data'
        required: false
    customHeaders:
        description: 'Custom HTTP Headers'
        required: false
outputs:
    body: 
        description: 'HTTP Response Content'
    headers:
        description: 'HTTP Response Headers'

runs:
    # using: 'node12'
    # main: 'dist/index.js'
    using: 'docker'
    image: 'Dockerfile'
