name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        id: myRequest
        uses: fjogeleit/http-request-action@v1.8.0
        with:
          url: 'https://httpbin.org/ip'
          method: 'GET'
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.response }}
