on: [push, pull_request]

jobs:
  http2-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Request
        id: registerReq
        uses: ./
        with:
          url: 'https://nghttp2.org/httpbin/ip'
          method: 'GET'
          http2: true
      - name: Show Response Headers
        run: echo ${{ registerReq.outputs.headers }}
      - name: Show Response Body
        run: echo ${{ registerReq.outputs.body }}
