on: [push]

jobs:
  http2-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check glibc version
        run: echo $(ldd --version)
      - name: Test Request
        id: registerReq
        uses: ./
        with:
          url: 'https://nghttp2.org/httpbin/anything'
          method: 'POST'
          headers: '{"test": "bruh"}'
          json: '{"hi": "there"}'
          httpVersion: '11'
      - name: Show Response Headers
        run: echo ${{ steps.registerReq.outputs.headers }}
      - name: Show Response Body
        run: echo ${{ steps.registerReq.outputs.body }}
