# name: request
# on: [push]
# jobs:
#   Request-Send:
#     runs-on: ubuntu-latest
#     steps:
#     - name: HTTP Request Action
#       id: registerReq
#       uses: fjogeleit/http-request-action@v1.8.0
#       with:
#         url: 'https://httpbin.org/ip'
#         method: 'GET'
#     - name: Show Response
#       run: echo ${{ steps.registerReq.outputs.response }}
name: Test

on: [push, pull_request]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Test Request
        id: registerReq
        uses: ./
        with:
          url: 'https://httpbin.org/ip'
          method: 'GET'
      - name: Show Response
        run: echo ${{ steps.registerReq.outputs.response }}

      - name: Request Postman Echo GET
        uses: ./
        with:
          url: 'https://postman-echo.com/get'
          method: 'GET'
      
      - name: Request Postman Echo POST
        uses: ./
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
          data: '{ "key": "value" }'
      
      - name: Request Postman Echo POST with Unescaped Newline
        uses: ./
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
          escapeData: 'true'
          data: >-
            {
              "key":"multi line\ntest
              text"
            }
      
      - name: Request Postman Echo BasicAuth
        uses: ./
        with:
          url: 'https://postman-echo.com/basic-auth'
          method: 'GET'
          username: 'postman'
          password: 'password'
      
      - name: Request Postman Echo with 404 Response and ignore failure code
        uses: ./
        with:
          url: 'https://postman-echo.com/status/404'
          method: 'GET'
          ignoreStatusCodes: '404'
      
      - name: Create Test File
        run: |
          echo "test" > testfile.txt

      - name: Request Postman Echo POST Multipart
        uses: ./
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
          data: '{ "key": "value" }'
          files: '{ "file": "${{ github.workspace }}/testfile.txt" }'
